// Minimal OpenAPI 3.0 types for code-gen (openapi-types is not a project dependency).

export interface GeneratedFile {
  path: string
  content: string
}

export interface OpenApiOperationObject {
  operationId?: string
  summary?: string
  description?: string
  tags?: string[]
  parameters?: unknown[]
  requestBody?: unknown
  responses?: Record<string, unknown>
}

export interface OpenApiPathItemObject {
  get?: OpenApiOperationObject
  post?: OpenApiOperationObject
  put?: OpenApiOperationObject
  delete?: OpenApiOperationObject
  patch?: OpenApiOperationObject
}

export interface OpenApiSchemaObject {
  type?: string | string[]
  properties?: Record<string, OpenApiSchemaObject | undefined>
  required?: string[]
  items?: OpenApiSchemaObject
  enum?: unknown[]
  $ref?: string
  description?: string
}

export interface OpenApiDocument {
  info?: { title?: string; version?: string; description?: string }
  servers?: Array<{ url?: string; description?: string }>
  paths?: Record<string, OpenApiPathItemObject | undefined>
  components?: {
    schemas?: Record<string, OpenApiSchemaObject | undefined>
  }
}

export function generateTypeScriptSdk(spec: OpenApiDocument): GeneratedFile[] {
  return [generateTypesFile(spec), generateClientFile(spec)]
}

function generateTypesFile(spec: OpenApiDocument): GeneratedFile {
  const schemas = spec.components?.schemas ?? {}
  const lines: string[] = [
    "// Generated by Reqly — do not edit manually",
    `// Source: ${spec.info?.title ?? "API"} v${spec.info?.version ?? "1.0.0"}`,
    "",
  ]

  let schemaCount = 0
  for (const [name, schema] of Object.entries(schemas)) {
    if (!schema || schema.$ref) continue
    schemaCount++
    const typeName = pascalCase(name)

    if (schema.type === "array" || schema.enum || isPrimitiveAlias(schema)) {
      // Emit as type alias: arrays, enums, primitive aliases
      lines.push(`export type ${typeName} = ${schemaToTsType(schema, spec)};`)
      lines.push("")
      continue
    }

    lines.push(`export interface ${typeName} {`)
    if (schema.properties) {
      for (const [propName, propSchema] of Object.entries(schema.properties)) {
        if (!propSchema) continue
        const required = schema.required?.includes(propName) ?? false
        const opt = required ? "" : "?"
        const type = schemaToTsType(propSchema, spec)
        lines.push(`  ${propName}${opt}: ${type};`)
      }
    }
    lines.push(`}`)
    lines.push("")
  }

  if (schemaCount === 0) {
    lines.push("// No schemas defined in this spec")
    lines.push("")
  }

  return { path: "types.ts", content: lines.join("\n") }
}

function generateClientFile(spec: OpenApiDocument): GeneratedFile {
  const baseUrl = spec.servers?.[0]?.url ?? ""
  const lines: string[] = [
    "// Generated by Reqly — do not edit manually",
    `// Source: ${spec.info?.title ?? "API"} v${spec.info?.version ?? "1.0.0"}`,
    "",
    `const BASE_URL = "${baseUrl}";`,
    "",
    "export interface RequestOptions {",
    "  headers?: Record<string, string>;",
    "  query?: Record<string, string | number | boolean>;",
    "  body?: unknown;",
    "}",
    "",
  ]

  let opCount = 0
  if (spec.paths) {
    for (const [path, pathItem] of Object.entries(spec.paths)) {
      if (!pathItem) continue
      const methods: Array<[string, OpenApiOperationObject | undefined]> = [
        ["get", pathItem.get],
        ["post", pathItem.post],
        ["put", pathItem.put],
        ["delete", pathItem.delete],
        ["patch", pathItem.patch],
      ]
      for (const [method, op] of methods) {
        if (!op) continue
        opCount++
        const opName = camelCase(op.operationId ?? `${method}_${path.replace(/[^a-z0-9]/gi, "_")}`)
        const params = extractPathParams(path)
        const pathSig = params.map((p) => `${p}: string`).join(", ")
        const pathReplace = params.reduce(
          (acc, p) => acc.replace(`{${p}}`, `\${${p}}`),
          path,
        )
        lines.push(
          `export async function ${opName}(${pathSig} options: RequestOptions = {}): Promise<unknown> {`,
        )
        lines.push(`  const url = new URL(\`${pathReplace}\`, BASE_URL);`)
        lines.push(`  if (options.query) {`)
        lines.push(
          `    for (const [k, v] of Object.entries(options.query)) url.searchParams.set(k, String(v));`,
        )
        lines.push(`  }`)
        lines.push(`  const res = await fetch(url.toString(), {`)
        lines.push(`    method: "${method.toUpperCase()}",`)
        lines.push(
          `    headers: { "Content-Type": "application/json", ...options.headers },`,
        )
        lines.push(`    body: options.body ? JSON.stringify(options.body) : undefined,`)
        lines.push(`  });`)
        lines.push(`  return res.json();`)
        lines.push(`}`)
        lines.push("")
      }
    }
  }

  if (opCount === 0) {
    lines.push("// No operations defined in this spec")
    lines.push("")
  }

  return { path: "client.ts", content: lines.join("\n") }
}

function isPrimitiveAlias(schema: OpenApiSchemaObject): boolean {
  const t = schema.type
  if (Array.isArray(t)) {
    return t.every(
      (x) =>
        x === "string" ||
        x === "number" ||
        x === "integer" ||
        x === "boolean" ||
        x === "null",
    )
  }
  return (
    t === "string" ||
    t === "number" ||
    t === "integer" ||
    t === "boolean" ||
    t === "null"
  )
}

function schemaToTsType(schema: OpenApiSchemaObject, spec: OpenApiDocument): string {
  if (schema.$ref) {
    const refName = schema.$ref.replace("#/components/schemas/", "")
    return pascalCase(refName)
  }
  if (schema.enum) {
    return schema.enum.map((v) => JSON.stringify(v)).join(" | ")
  }
  if (schema.type === "array") {
    if (schema.items) return `${schemaToTsType(schema.items, spec)}[]`
    return "unknown[]"
  }
  if (schema.type === "object" || schema.properties) {
    return "Record<string, unknown>"
  }
  if (Array.isArray(schema.type)) {
    const nonNull = schema.type.filter((t) => t !== "null")
    return nonNull.map((t) => primitiveToTsType(t)).join(" | ")
  }
  return primitiveToTsType(schema.type as string)
}

function primitiveToTsType(type: string): string {
  switch (type) {
    case "string":
      return "string"
    case "number":
    case "integer":
      return "number"
    case "boolean":
      return "boolean"
    case "null":
      return "null"
    case "object":
      return "Record<string, unknown>"
    case "array":
      return "unknown[]"
    default:
      return "unknown"
  }
}

function pascalCase(s: string): string {
  return s
    .replace(/[^a-zA-Z0-9]+/g, " ")
    .split(" ")
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("")
}

function camelCase(s: string): string {
  const p = pascalCase(s)
  return p.charAt(0).toLowerCase() + p.slice(1)
}

function extractPathParams(path: string): string[] {
  const matches = path.matchAll(/\{([^}]+)\}/g)
  return Array.from(matches, (m) => m[1])
}
